server:
  port: "3000"

database:
  host: "localhost"
  user: "postgres"
  password: "pass123"
  name: "indego_db"
  port: "5432"
  sslmode: "disable"

indego:
  base_url: "https://www.rideindego.com/stations/json/"

weather:
  base_url: "https://api.openweathermap.org/data/2.5/weather"
  api_key: "01d648cf01dbfff013982e461ed5aaf5"
